# This file was generated by GoReleaser. DO NOT EDIT.
class PanIndex < Formula
  desc ""
  homepage ""
  version "1.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/libsgh/PanIndex/releases/download/v1.0.4/PanIndex_1.0.4_darwin_amd64.tar.gz"
    sha256 "8fd8edfe397451c0b79a60bc9515a3b75c9ca93539f3f9d71aa0d8b7fdc48b05"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/libsgh/PanIndex/releases/download/v1.0.4/PanIndex_1.0.4_linux_amd64.tar.gz"
      sha256 "68bf3f5b4c4ac0e6a02aaee7ced08005cc1d22ba4d369f132aa84549520c3b00"
    end
  end

  def install
    bin.install "packr2"
  end
end
